<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Entreprise_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function get_entreprise($id_entreprise)
    {
        return $this->db->get_where('entreprise',array('id_entreprise'=>$id_entreprise))->row_array();
    }

    function get_entreprise_by_telephone_contact($telephone_contact)
    {
        return $this->db->get_where('entreprise',array('telephone_contact'=>$telephone_contact))->row_array();
    }


    function get_entreprise_by_token($token)
    {
        return $this->db->get_where('entreprise',array('token_entreprise'=>$token))->row_array();
    }
      
    function get_all_entreprises()
    {
        $this->db->order_by('id_entreprise', 'desc');
        return $this->db->get('entreprise')->result_array();
    }
     
    function add_entreprise($params)
    {
        $this->db->insert('entreprise',$params);
        return $this->db->insert_id();
    }
    
    function update_entreprise($id_entreprise, $params)
    {
        $this->db->where('id_entreprise',$id_entreprise);
        return $this->db->update('entreprise',$params);
    }
    
    function delete_entreprise($token)
    {
        $this->db->where("token_entreprise", $token);
        return $this->db->delete("entreprise");
    }

    function get_all_entreprise_order_by_name(){
        $this->db->where("is_deleted", 0);
        $this->db->order_by("nom_entreprise", 'asc');
        return $this->db->get('entreprise')->result_array();
    }

    function get_entreprise_by_type_entreprise($type){
        return $this->db->get_where("entreprise", array("id_type_entreprise" => $type, 'is_deleted' => 0))->result_array();
    }


    function get_transitaire_by_num_transitaire($num_transitaire){
        return $this->db->get_where("entreprise", array("numero_transitaire	" => $num_transitaire, 'is_deleted' => 0))->row_array();
    }

    function get_importateur_exportateur(){
        return $this->db->get_where("entreprise", array("id_type_entreprise" => 1, 'is_deleted' => 0))->result_array();
    }
}