<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Etat_civil_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get etat_civils by id_etat_civil
     */
    function get_etat_civils($id_etat_civil)
    {
        return $this->db->get_where('etat_civil',array('id_etat_civil'=>$id_etat_civil, 'is_deleted' => 0))->row_array();
    }

    function get_etat_by_token($token){
        return $this->db->get_where('etat_civil',array('token_etat_civil'=>$token, 'is_deleted' => 0))->row_array();
    }
        
    /*
     * Get all etat_civil
     */
    function get_all_etat_civil()
    {
        $this->db->where('is_deleted', 0);
        $this->db->order_by('id_etat_civil', 'desc');
        return $this->db->get('etat_civil')->result_array();
    }
        
    /*
     * function to add new etat_civils
     */
    function add_etat_civils($params)
    {
        $this->db->insert('etat_civil',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update etat_civils
     */
    function update_etat_civils($id_etat_civil,$params)
    {
        $this->db->where('id_etat_civil',$id_etat_civil);
        return $this->db->update('etat_civil',$params);
    }
    
    /*
     * function to delete etat_civils
     */
    function delete_etat_civil($token)
    {
        $this->db->where("token_etat_civil", $token);
        $this->db->set("is_deleted", 1);
        return $this->db->update("etat_civil");
    }


    function add_etat_bloquer($params)
    {
        $this->db->insert('etat_bloquer',$params);
        return $this->db->insert_id();
    }


}