<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Type_entreprise_model extends CI_Model
{
    function add($params){
        $this->db->insert("type_entreprise", $params);
        return $this->db->insert_id();
    }

    function update($id, $params){
        $this->db->where("id_type_entreprise", $id);
        return $this->db->update("type_entreprise", $params);
    }

    function get_all_type_entreprises(){
        $this->db->where('is_deleted', 0);
        $this->db->order_by('id_type_entreprise', 'desc');
        return $this->db->get('type_entreprise')->result_array();
    }

    function get_type_by_token($token){
        return $this->db->get_where('type_entreprise',array('token_type_entreprise'=>$token, 'is_deleted' => 0))->row_array();
    }

    function get_type($id){
        return $this->db->get_where('type_entreprise',array('id_type_entreprise'=>$id, 'is_deleted' => 0))->row_array();
    }

    function delete_type($token){
        $this->db->where("token_type_entreprise", $token);
        $this->db->set("is_deleted", 1);
        return $this->db->update("type_entreprise");
    }
}